import datetime

def generate_report(results, image_name):
    """
    Generates a clinical diagnostic report in Markdown format.
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = f"""# 📑 Clinical Diagnostic Report: Breast Cancer AI Analysis
**Generated on:** {now}  
**Source Image:** {image_name}

---

## 🔍 Executive Summary
- **Primary Diagnosis:** {"TUMOR DETECTED" if results['tumor_present'] else "NORMAL / NO TUMOR DETECTED"}
- **Detection Count:** {len(results['findings'])} suspicious region(s) identified.
- **Overall Tumor-to-Breast Ratio:** {results['overall_ratio']:.2%}

---

## 📊 Detailed Findings
"""
    
    if not results['findings']:
        report += "\n**No suspicious regions were identified in this diagnostic sequence.**\n"
    else:
        for i, finding in enumerate(results['findings']):
            color = "🔴 MALIGNANT" if finding['is_malignant'] else "🟢 BENIGN"
            report += f"""
### Finding #{i+1}: {finding['classification']}
- **Status:** {color}
- **Staging:** {finding['stage']}
- **Anatomical Location:** {finding.get('location_pct', 'N/A')} (Relative Coordinates)
- **Tumor Size:** {finding.get('area_pixels', 'N/A')} pixels
- **Density Index (Radiopacity):** {finding.get('density_index', 'N/A')}
"""

    report += """
---

## 🛠️ System Configuration & Methodology
- **Deep Learning Backbone:** VGG16 (Optimized for Breast Histology)
- **Segmentation Engine:** UNet (High-Precision Contour Detection)
- **Patch Strategy:** Adaptive multi-patch reconstruction
- **Processing Backend:** PyTorch Neural Engine

---
**Disclaimer:** This report is generated by an Artificial Intelligence system for research and auxiliary diagnostic purposes. Final clinical decisions should be made by a qualified medical professional.
"""
    return report
